title: Umair Mughal
logo: /assests/img/headshot.jpg
description: I am a PhD Candidate at the Computer Science Department at Tennessee Tech University. 
email: uamughal42@tntech.edu
#show_downloads: true
theme: jekyll-theme-minimal
