title: Umair Mughal
logo: /assests/img/headshot.jpg
description: I am a PhD Candidate at the Computer Science Department at Tennessee Tech University. 

email: uamughal42@tntech.edu

google_scholar: https://scholar.google.com/citations?user=yIQfpKIAAAAJ&view_op=list_works&sortby=pubdate
linkedin: https://www.linkedin.com/in/umair-mughal-490715174


#show_downloads: true
theme: jekyll-theme-minimal
