title: Umair Mughal
logo: /assests/img/headshot.jpg
I am a PhD Candidate at the Computer Science Department at Tennessee Tech University.
Email: uamughal42@tntech.edu
#show_downloads: true
theme: jekyll-theme-minimal
